### ISSUE TITLE
able to change distance from bottom/left/rigth

### ISSUE THREAD

**Issue by brainmaniac** [insites/cookieconsent#236]
Thank you for a awesome tool! Highly appreciated.

My only note is that I would really love to be able to modify the distance to bottom/left/rigth when using the boxes in the corners..

**Comment by alexmorleyfinch** [comment]
You can do this by adding a new style:

```css
.cc-window {
  left: 500px; // left, right, top or bottom
}
```
