### ISSUE TITLE
Cookie Banner hides footer links like imprint or data privacy

### ISSUE THREAD

**Issue by rrdd** [insites/cookieconsent#333]
Hello,

is there a way to show the cookie banner below the page content and not over? currently the cookie banner hides important links in a lot of page footers. often you find imprint or data privacy links there.

regards

**Comment by InsanityMeetsHH** [comment]
You can do this with CSS. If you have a wrapper div around your content.
```css
.cc-window ~ div.container {
    padding-bottom: 50px;
}
```
